# Generated by Django 3.1 on 2021-02-17 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universe', models.CharField(choices=[('DC COMICS', 'DC COMICS'), ('MARVEL', 'MARVEL')], max_length=9)),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('description', models.TextField(max_length=100, verbose_name='description')),
                ('stared', models.BooleanField(default=False)),
                ('height', models.IntegerField()),
                ('weigth', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('power', models.FloatField()),
                ('super_hero_image', models.ImageField(default='none.jpg', upload_to='static')),
                ('account_id', models.ForeignKey(blank=True, db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SuperHero',
            },
        ),
    ]
