# Generated by Django 3.1 on 2021-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheros', '0002_auto_20210217_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='name'),
        ),
    ]
