# Generated by Django 3.1 on 2021-02-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superheros', '0001_initial'),
        ('combats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='a_tie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combat',
            name='winner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='superheros.superhero'),
        ),
        migrations.AlterUniqueTogether(
            name='combat',
            unique_together={('first_superhero', 'second_superhero')},
        ),
        migrations.RemoveField(
            model_name='combat',
            name='started_at',
        ),
    ]
