# Generated by Django 3.1 on 2021-02-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheros', '0001_initial'),
        ('combats', '0002_auto_20210217_0913'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='combat',
            unique_together={('first_superhero', 'first_superhero')},
        ),
    ]
