# Generated by Django 3.1 on 2021-02-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0003_auto_20210217_0914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='combat',
            unique_together=set(),
        ),
    ]
